version: "1"

services:
  chat_server_db:
    image: postgres
    restart: always
    container_name: chat_server_postgres
    ports:
      - 8080:8080
    environment:
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres
  rocket:
    build: .
    command: bash -c "cargo run"
    links:
      - chat_server_db
    ports:
      - 8000:8000